### ISSUE TITLE
Cannot find module 'semver'

### ISSUE THREAD

**Issue by mtharrison** [hapijs/scooter#44]
Seems like since explicit semver dependency was removed in this commit https://github.com/hapijs/scooter/commit/f9cdc670d2454ca18a77e95ec43dfd2b0fe80e9c the plugin is broken.

This is because the dependency useragent uses but does not depend on semver (only specified as a dev dep). https://github.com/3rd-Eden/useragent/blob/master/package.json#L40

Example:

```js
const Hapi = require('hapi');
const server =  Hapi.server({ port: 8086 });
const Scooter = require('scooter');

server.route({
    method: 'GET',
    path: '/user-agent',
    handler: (request, reply) => {

        return reply(request.plugins.scooter.toJSON());
    }
});

const start = async () => {

    await server.register(Scooter);

    await server.start();

    console.log(server.info.uri + '/user-agent');
};

start();
```

When using hapi 17.8.1 and scooter 5.0.1 and installing deps with `--production` flag the example code above will throw:

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'semver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/matt/Desktop/scooter-test/node_modules/useragent/features/index.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by mtharrison** [comment]
I was going to open an issue on useragent but their readme says "As [features] requires the semver module to function you need to install it seperately".
